version: "3"

services:
  app:
    build: ./
    tty: true
    ports:
      - 4000:4000
    volumes:
      - ./:/app/
      - /app/node_modules
    depends_on: 
      - db
      - adminer
    command: "npm run dev"
  
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes: 
      - ./DB:/var/lib/mysql

  adminer:
    image: adminer
    ports:
      - 8080:8080
    depends_on: 
      - db
